name: Build All Platforms

on:
  push:
    branches: [ "main" ]

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl
    - name: Package with PyInstaller
      run: pyinstaller --onedir -n grade-conv main.py
    - name: Compress Windows Output
      run: Compress-Archive -Path dist/grade-conv/* -DestinationPath dist/grade-conv-windows.zip
    - uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: dist/grade-conv-windows.zip


  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl
    - name: Package with PyInstaller
      env:
        MACOSX_DEPLOYMENT_TARGET: "11.0"
      run: pyinstaller --onedir --target-arch universal2 -n grade-conv main.py
    - name: Compress Mac Output
      run: cd dist/grade-conv && zip -r ../grade-conv-mac.zip .
    - uses: actions/upload-artifact@v4
      with:
        name: build-mac
        path: dist/grade-conv-mac.zip


  package:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: build-windows
        path: tmp/
    - uses: actions/download-artifact@v4
      with:
        name: build-mac
        path: tmp/
    - name: Extract and organize
      run: |
        mkdir -p "release/for Microsoft Windows"
        mkdir -p "release/for Apple Macintosh"
        unzip tmp/grade-conv-windows.zip -d "release/for Microsoft Windows/"
        unzip tmp/grade-conv-mac.zip -d "release/for Apple Macintosh/"
        cp README.md release/
    - uses: actions/upload-artifact@v4
      with:
        name: grade-conv
        path: release/
